apiVersion: v1
kind: Service
metadata:
  name: my-cats-and-dogs-svc
  labels:
    app: cats-and-dogs
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: cats-and-dogs
