apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cats-and-dogs-pv-claim-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
